# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import project1.project1.topics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('topic_image_width_field', models.IntegerField()),
                ('topic_image_height_field', models.IntegerField()),
                ('topic_image', models.ImageField(blank=True, height_field='topic_image_height_field', upload_to=project1.project1.topics.models.get_upload_location, width_field='topic_image_width_field')),
            ],
        ),
    ]
