# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import project1.project1.topics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to=project1.project1.topics.models.get_upload_location)),
                ('description', models.TextField()),
            ],
        ),
    ]
