# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import project1.project1.topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_image_height_field',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_image_width_field',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_image',
            field=models.ImageField(blank=True, upload_to=project1.project1.topics.models.get_upload_location),
        ),
    ]
