# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170702_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_image',
            new_name='image',
        ),
    ]
