# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import project1.project1.topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20170705_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project1.project1.topics.models.get_upload_location),
        ),
    ]
