# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuser',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='PostUser',
        ),
    ]
