# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170504_1542'),
        ('posts', '0002_auto_20170504_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_disliked', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_posts', through='posts.Like', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='disliked_by',
            field=models.ManyToManyField(null=True, related_name='disliked_posts', through='posts.Dislike', to='profiles.Profile'),
        ),
    ]
