# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170504_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-date_liked']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='disliked_by',
            new_name='dislikers',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='likers',
        ),
    ]
