# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tagpost'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tagged', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profilefollow',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='profilefollow',
            name='source',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.DeleteModel(
            name='ProfileFollow',
        ),
        migrations.AddField(
            model_name='profiletag',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profiletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(through='profiles.ProfileTag', to='tags.Tag'),
        ),
    ]
