# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'ordering': ['-date_followed']},
        ),
    ]
