# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_credential',
            new_name='credential',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_major',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_residence',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_school',
            new_name='school',
        ),
    ]
