# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170504_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra',
            new_name='Follow',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='followers', through='profiles.Follow', to='profiles.Profile'),
        ),
    ]
