# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(null=True, to='profiles.Profile'),
        ),
    ]
