# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170524_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='occupations',
            new_name='occupation',
        ),
    ]
