# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170409_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='profile_avatar/1.jpg', upload_to='profile_avatar/'),
        ),
    ]
