# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170524_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='profile_company',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='profile_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='major',
            new_name='profile_major',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='occupation',
            new_name='profile_occupation',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='position',
            new_name='profile_position',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='residence',
            new_name='profile_residence',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='profile_school',
        ),
    ]
