# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170529_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
    ]
