# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170530_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_gender',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
