# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170530_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='z', max_length=1),
        ),
    ]
