# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
