# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20170715_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nav',
            new_name='main',
        ),
    ]
