# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170819_0927'),
        ('tags', '0003_tagpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(through='tags.TagPost', to='posts.Post'),
        ),
    ]
